[tool.poetry]
name = "2024-google-extended"
version = "0.1.0"
description = ""
authors = ["Pedro Rivera <ppsirg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
hovercraft = "^2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
